"""fix_alumna_schema_final

Revision ID: 001f92f5438b
Revises: 80da0ddd2420
Create Date: 2026-05-09 16:07:38.944013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001f92f5438b'
down_revision: Union[str, Sequence[str], None] = '80da0ddd2420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnas', sa.Column('nivel', sa.String(), nullable=True))
    op.alter_column('alumnas', 'combo_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('alumnas', 'docente_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnas', 'nivel')
    # ### end Alembic commands ###
