"""add_gasto_fields

Revision ID: 14e23465f6d5
Revises: 5125b33f80c8
Create Date: 2026-05-09 15:01:28.347500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e23465f6d5'
down_revision: Union[str, Sequence[str], None] = '5125b33f80c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('mes', sa.Integer(), nullable=True))
    op.add_column('gastos', sa.Column('anio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos', 'anio')
    op.drop_column('gastos', 'mes')
    # ### end Alembic commands ###
