"""add_alquiler_fields

Revision ID: 23f41f86f736
Revises: 865517824c00
Create Date: 2026-05-09 14:38:25.467790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f41f86f736'
down_revision: Union[str, Sequence[str], None] = '865517824c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alquileres_sala', sa.Column('tarifa_aplicada', sa.Float(), nullable=True))
    op.add_column('alquileres_sala', sa.Column('pagado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alquileres_sala', 'pagado')
    op.drop_column('alquileres_sala', 'tarifa_aplicada')
    # ### end Alembic commands ###
