"""add_taller_fields

Revision ID: 5125b33f80c8
Revises: 23f41f86f736
Create Date: 2026-05-09 14:43:21.156769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5125b33f80c8'
down_revision: Union[str, Sequence[str], None] = '23f41f86f736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talleres', sa.Column('mes', sa.Integer(), nullable=True))
    op.add_column('talleres', sa.Column('anio', sa.Integer(), nullable=True))
    op.add_column('talleres', sa.Column('pago_facilitador_realizado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talleres', 'pago_facilitador_realizado')
    op.drop_column('talleres', 'anio')
    op.drop_column('talleres', 'mes')
    # ### end Alembic commands ###
