"""add_actividades_to_alumna

Revision ID: 80da0ddd2420
Revises: a8ffec1f602d
Create Date: 2026-05-09 15:51:25.835370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80da0ddd2420'
down_revision: Union[str, Sequence[str], None] = 'a8ffec1f602d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnas', sa.Column('actividades', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnas', 'actividades')
    # ### end Alembic commands ###
