"""add_cantidad_and_duracion_to_clasedocente

Revision ID: 818c8dcc5a1b
Revises: 20983def2ab7
Create Date: 2026-05-05 22:32:34.356188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818c8dcc5a1b'
down_revision: Union[str, Sequence[str], None] = '20983def2ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clases_docentes', sa.Column('cantidad_clases', sa.Integer(), nullable=True))
    op.add_column('clases_docentes', sa.Column('duracion', sa.Float(), nullable=True))
    op.alter_column('clases_docentes', 'mes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clases_docentes', 'anio',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clases_docentes', 'anio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clases_docentes', 'mes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('clases_docentes', 'duracion')
    op.drop_column('clases_docentes', 'cantidad_clases')
    # ### end Alembic commands ###
