"""add_configuraciones_table

Revision ID: 865517824c00
Revises: 818c8dcc5a1b
Create Date: 2026-05-05 22:33:15.086286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865517824c00'
down_revision: Union[str, Sequence[str], None] = '818c8dcc5a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=True),
    sa.Column('valor', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuraciones_clave'), 'configuraciones', ['clave'], unique=True)
    op.create_index(op.f('ix_configuraciones_id'), 'configuraciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuraciones_id'), table_name='configuraciones')
    op.drop_index(op.f('ix_configuraciones_clave'), table_name='configuraciones')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
