"""add_alumna_extended_fields

Revision ID: a3f889e8ad7b
Revises: 001f92f5438b
Create Date: 2026-05-23 19:57:24.336591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f889e8ad7b'
down_revision: Union[str, Sequence[str], None] = '001f92f5438b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnas', sa.Column('docente_ids', sa.String(), nullable=True))
    op.add_column('alumnas', sa.Column('dia_hora_clase', sa.String(), nullable=True))
    op.add_column('alumnas', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('alumnas', sa.Column('contacto_emergencia', sa.String(), nullable=True))
    op.add_column('alumnas', sa.Column('autoriza_imagen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnas', 'autoriza_imagen')
    op.drop_column('alumnas', 'contacto_emergencia')
    op.drop_column('alumnas', 'fecha_nacimiento')
    op.drop_column('alumnas', 'dia_hora_clase')
    op.drop_column('alumnas', 'docente_ids')
    # ### end Alembic commands ###
