"""link_docente_user

Revision ID: a8ffec1f602d
Revises: 14e23465f6d5
Create Date: 2026-05-09 15:24:11.022665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ffec1f602d'
down_revision: Union[str, Sequence[str], None] = '14e23465f6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'docentes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docentes', type_='foreignkey')
    op.drop_column('docentes', 'user_id')
    # ### end Alembic commands ###
